server:
  port: 8080
spring:
  application:
    name: tweet-service
  datasource:
    driver-class-name: ${DRIVER_DB:com.mysql.cj.jdbc.Driver}
    username: ${USER_DB:root}
    password: ${PASSWORD_DB:brtwcvv1}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tweet_database?useSSL=false
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl.auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #show-sql: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:9000/eureka

cloud:
  aws:
    stack:
      auto: false
      enabled: false
    region:
      static: us-west-1
    sqs:
      url: http://${SQS_URL:localhost}:4576