server:
  port: ${PORT:8084}
spring:
  application:
    name: tweet-service
  datasource:
    driver-class-name: ${DRIVER_DB:com.mysql.cj.jdbc.Driver}
    username: ${USER_DB:root}
    password: ${PASSWORD_DB:brtwcvv1}
    url: ${HOST_DB:jdbc:mysql://localhost:3306/tweet_database?useSSL=false}
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl.auto: update
    database-platform: ${DIALECT_DB:org.hibernate.dialect.MySQL5InnoDBDialect}
    show-sql: true

eureka:
  instance:
    non-secure-port: 80
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka}

cloud:
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    stack:
      auto: false
      enabled: false
    region:
      static: us-west-1
    sqs:
      url: http://${SQS_URL:localhost}:4576
    dynamodb:
      url: http://${DYNAMODB_URL:localhost}:4566