server:
  port: 8083
spring:
  application:
    name: timeline-service
  redis:
    database: 0
    host: localhost
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    timeout: 60000

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

cloud:
  aws:
    stack:
      auto: false
    #region: us-east-1
    sqs:
      url: http://localhost:4576