spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    timeout: 60000

eureka:
  instance:
    non-secure-port: 80
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

cloud:
  aws:
    accessKey: admin
    secretKey: admin
    stack:
      auto: false
      enabled: false
    region:
      static: us-west-1
    sqs:
      url: http://localhost:4576

client:
  user-followers:
    url: http://localhost:8081
