server:
  port: 9002
spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka}
      non-secure-port: 80
      secure-port: 443

jwt:
  secret: screte-value