server:
  port: ${PORT:9002}
spring:
  application:
    name: gateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9000/eureka}

jwt:
  secret: screte-value

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info