server:
  port: ${PORT:9000}
eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME_EUREKA:localhost}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    eviction-interval-timer-in-ms: 1000
