server:
  port: 9000
eureka:
  instance:
    hostname: ${HOSTNAME_EUREKA:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka/

  server:
    eviction-interval-timer-in-ms: 1500
