server:
  port: 9000
eureka:
  instance:
    hostname: ${HOSTNAME_EUREKA:localhost}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      non-secure-port: 80
      secure-port: 443

  server:
    eviction-interval-timer-in-ms: 1000
